# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='raft.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nraft.proto\"\x06\n\x04Void\"b\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\t\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\r\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\r\"C\n\x10RequestVoteReply\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\r\x12\x13\n\x0bvoteGranted\x18\x03 \x01(\r\"\x88\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\r\x12\x10\n\x08leaderId\x18\x02 \x01(\t\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\r\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\r\x12\x0f\n\x07\x65ntries\x18\x05 \x01(\x0c\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\r\"Z\n\x12\x41ppendEntriesReply\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\r\x12\x0f\n\x07success\x18\x03 \x01(\r\x12\x17\n\x0flastAgreedIndex\x18\x04 \x01(\r\"\x1f\n\x10\x41ppendLogRequest\x12\x0b\n\x03log\x18\x01 \x01(\t\"\x10\n\x0e\x41ppendLogReply\"\x13\n\x11RequestLogRequest\"-\n\x0fRequestLogReply\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0c\n\x04logs\x18\x02 \x03(\t2\xc2\x01\n\x04Raft\x12+\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x05.Void\"\x00\x12+\n\rOnRequestVote\x12\x11.RequestVoteReply\x1a\x05.Void\"\x00\x12/\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x05.Void\"\x00\x12/\n\x0fOnAppendEntries\x12\x13.AppendEntriesReply\x1a\x05.Void\"\x00\x32\x8e\x01\n\x07\x43ontrol\x12\x31\n\tAppendLog\x12\x11.AppendLogRequest\x1a\x0f.AppendLogReply\"\x00\x12\x34\n\nRequestLog\x12\x12.RequestLogRequest\x1a\x10.RequestLogReply\"\x00\x12\x1a\n\x08Shutdown\x12\x05.Void\x1a\x05.Void\"\x00\x62\x06proto3')
)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=20,
)


_REQUESTVOTEREQUEST = _descriptor.Descriptor(
  name='RequestVoteRequest',
  full_name='RequestVoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='RequestVoteRequest.term', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='candidateId', full_name='RequestVoteRequest.candidateId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastLogIndex', full_name='RequestVoteRequest.lastLogIndex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastLogTerm', full_name='RequestVoteRequest.lastLogTerm', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=120,
)


_REQUESTVOTEREPLY = _descriptor.Descriptor(
  name='RequestVoteReply',
  full_name='RequestVoteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='RequestVoteReply.from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='term', full_name='RequestVoteReply.term', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voteGranted', full_name='RequestVoteReply.voteGranted', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=189,
)


_APPENDENTRIESREQUEST = _descriptor.Descriptor(
  name='AppendEntriesRequest',
  full_name='AppendEntriesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='AppendEntriesRequest.term', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leaderId', full_name='AppendEntriesRequest.leaderId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prevLogIndex', full_name='AppendEntriesRequest.prevLogIndex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prevLogTerm', full_name='AppendEntriesRequest.prevLogTerm', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entries', full_name='AppendEntriesRequest.entries', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leaderCommit', full_name='AppendEntriesRequest.leaderCommit', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=328,
)


_APPENDENTRIESREPLY = _descriptor.Descriptor(
  name='AppendEntriesReply',
  full_name='AppendEntriesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='AppendEntriesReply.from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='term', full_name='AppendEntriesReply.term', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='AppendEntriesReply.success', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastAgreedIndex', full_name='AppendEntriesReply.lastAgreedIndex', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=420,
)


_APPENDLOGREQUEST = _descriptor.Descriptor(
  name='AppendLogRequest',
  full_name='AppendLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log', full_name='AppendLogRequest.log', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=453,
)


_APPENDLOGREPLY = _descriptor.Descriptor(
  name='AppendLogReply',
  full_name='AppendLogReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=471,
)


_REQUESTLOGREQUEST = _descriptor.Descriptor(
  name='RequestLogRequest',
  full_name='RequestLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=492,
)


_REQUESTLOGREPLY = _descriptor.Descriptor(
  name='RequestLogReply',
  full_name='RequestLogReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='RequestLogReply.role', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logs', full_name='RequestLogReply.logs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=539,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['RequestVoteRequest'] = _REQUESTVOTEREQUEST
DESCRIPTOR.message_types_by_name['RequestVoteReply'] = _REQUESTVOTEREPLY
DESCRIPTOR.message_types_by_name['AppendEntriesRequest'] = _APPENDENTRIESREQUEST
DESCRIPTOR.message_types_by_name['AppendEntriesReply'] = _APPENDENTRIESREPLY
DESCRIPTOR.message_types_by_name['AppendLogRequest'] = _APPENDLOGREQUEST
DESCRIPTOR.message_types_by_name['AppendLogReply'] = _APPENDLOGREPLY
DESCRIPTOR.message_types_by_name['RequestLogRequest'] = _REQUESTLOGREQUEST
DESCRIPTOR.message_types_by_name['RequestLogReply'] = _REQUESTLOGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:Void)
  })
_sym_db.RegisterMessage(Void)

RequestVoteRequest = _reflection.GeneratedProtocolMessageType('RequestVoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOTEREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:RequestVoteRequest)
  })
_sym_db.RegisterMessage(RequestVoteRequest)

RequestVoteReply = _reflection.GeneratedProtocolMessageType('RequestVoteReply', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOTEREPLY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:RequestVoteReply)
  })
_sym_db.RegisterMessage(RequestVoteReply)

AppendEntriesRequest = _reflection.GeneratedProtocolMessageType('AppendEntriesRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:AppendEntriesRequest)
  })
_sym_db.RegisterMessage(AppendEntriesRequest)

AppendEntriesReply = _reflection.GeneratedProtocolMessageType('AppendEntriesReply', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESREPLY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:AppendEntriesReply)
  })
_sym_db.RegisterMessage(AppendEntriesReply)

AppendLogRequest = _reflection.GeneratedProtocolMessageType('AppendLogRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPENDLOGREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:AppendLogRequest)
  })
_sym_db.RegisterMessage(AppendLogRequest)

AppendLogReply = _reflection.GeneratedProtocolMessageType('AppendLogReply', (_message.Message,), {
  'DESCRIPTOR' : _APPENDLOGREPLY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:AppendLogReply)
  })
_sym_db.RegisterMessage(AppendLogReply)

RequestLogRequest = _reflection.GeneratedProtocolMessageType('RequestLogRequest', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTLOGREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:RequestLogRequest)
  })
_sym_db.RegisterMessage(RequestLogRequest)

RequestLogReply = _reflection.GeneratedProtocolMessageType('RequestLogReply', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTLOGREPLY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:RequestLogReply)
  })
_sym_db.RegisterMessage(RequestLogReply)



_RAFT = _descriptor.ServiceDescriptor(
  name='Raft',
  full_name='Raft',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=542,
  serialized_end=736,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestVote',
    full_name='Raft.RequestVote',
    index=0,
    containing_service=None,
    input_type=_REQUESTVOTEREQUEST,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OnRequestVote',
    full_name='Raft.OnRequestVote',
    index=1,
    containing_service=None,
    input_type=_REQUESTVOTEREPLY,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AppendEntries',
    full_name='Raft.AppendEntries',
    index=2,
    containing_service=None,
    input_type=_APPENDENTRIESREQUEST,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OnAppendEntries',
    full_name='Raft.OnAppendEntries',
    index=3,
    containing_service=None,
    input_type=_APPENDENTRIESREPLY,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RAFT)

DESCRIPTOR.services_by_name['Raft'] = _RAFT


_CONTROL = _descriptor.ServiceDescriptor(
  name='Control',
  full_name='Control',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=739,
  serialized_end=881,
  methods=[
  _descriptor.MethodDescriptor(
    name='AppendLog',
    full_name='Control.AppendLog',
    index=0,
    containing_service=None,
    input_type=_APPENDLOGREQUEST,
    output_type=_APPENDLOGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RequestLog',
    full_name='Control.RequestLog',
    index=1,
    containing_service=None,
    input_type=_REQUESTLOGREQUEST,
    output_type=_REQUESTLOGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Shutdown',
    full_name='Control.Shutdown',
    index=2,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROL)

DESCRIPTOR.services_by_name['Control'] = _CONTROL

# @@protoc_insertion_point(module_scope)
