[server]
name="test0"
addr="127.0.0.1:23333"

[[clusters]]
name="test0"
addr="127.0.0.1:23333"

[[clusters]]
name="test1"
addr="127.0.0.1:23334"

[[clusters]]
name="test2"
addr="127.0.0.1:23335"

[[clusters]]
name="test3"
addr="127.0.0.1:23336"

[[clusters]]
name="test4"
addr="127.0.0.1:23337"
